### ISSUE TITLE
Pull Issue between Github Community Repos and Akash Website

### ISSUE THREAD

**Issue by brewsterdrinkwater** [akash-network/website-5-archive#100]
## Description

The [Akash website community groups side menu](https://akash.network/community/) is not pulling data properly from the [Github community groups](https://github.com/akash-network/community). Many of the pages on the website are pulling old information or 404 errors.

### Steps to reproduce

**Link works properly on Github** - https://github.com/akash-network/community/blob/main/sig-clients/meetings/001-2023-01-19.md
**Links for meeting notes are retrieving "404" error via website** -https://akash.network/community/core-groups/sig-clients/meetings/001-2023-01-19

### Desired Outcome:

The fix would be to pull the information from Github in real time to the website, so as changes are made to Github community repos, those changes show up on the website quickly.

**Comment by brewsterdrinkwater** [comment]
https://docs.github.com/en/get-started/using-git/getting-changes-from-a-remote-repository

**Comment by ghost** [comment]
Finally got to check this.

Looking:

1. Greg's [commit](https://github.com/akash-network/website/commit/e825c83057cf1d959eab6c6950fecfb6d50893c5) to update [the Akash Network Community Groups (CGs) page](https://github.com/akash-network/website/blob/main/content/en/community/core-groups/cg-list/index.md) page failed
![image](https://github.com/akash-network/website/assets/107317698/a8576836-1c39-4f4b-8733-99c9c92665bf)

2. Clicking on :x: shows the Cloudflare bit failed
![image](https://github.com/akash-network/website/assets/107317698/f187a3e7-765d-4582-b6bb-9d7a1cef132b)

3. `Details` leading to the GH Actions page with the [failed](https://github.com/akash-network/website/runs/13972362824) Cloudflare Pages build job.
![image](https://github.com/akash-network/website/assets/107317698/af9fc08e-dac4-401a-98ee-5aefde90839c)

4. `View logs` leads to the [logs page](https://dash.cloudflare.com/fa0186293ce6df59a669b879db591361/pages/view/website/182ec858-7388-4bdf-a5d5-78373794c408) at Cloudflare

![image](https://github.com/akash-network/website/assets/107317698/991a01bb-f31d-4782-b423-e07d47296762)

![image](https://github.com/akash-network/website/assets/107317698/a9e70ed6-1fc5-4e1e-80a2-44f3da4c09c3)

Logs:

```
2023-06-03T00:39:22.062267Z	Cloning repository...
2023-06-03T00:39:31.069022Z	From https://github.com/akash-network/website
2023-06-03T00:39:31.069666Z	 * branch            e825c83057cf1d959eab6c6950fecfb6d50893c5 -> FETCH_HEAD
2023-06-03T00:39:31.070366Z	
2023-06-03T00:39:32.939425Z	HEAD is now at e825c83 community: fix links
2023-06-03T00:39:32.940258Z	
2023-06-03T00:39:34.109591Z	Submodule 'stage/community' (https://github.com/akash-network/community.git) registered for path 'stage/community'
2023-06-03T00:39:34.110341Z	Cloning into '/opt/buildhome/clone/stage/community'...
2023-06-03T00:39:34.110527Z	Submodule path 'stage/community': checked out '0d2fa3bdf67e4016a17d0b377bb196275a21b6f5'
2023-06-03T00:39:34.110655Z	
2023-06-03T00:39:34.146661Z	Success: Finished cloning repository files
2023-06-03T00:39:34.786478Z	Installing dependencies
2023-06-03T00:39:34.794798Z	Python version set to 2.7
2023-06-03T00:39:37.805064Z	v12.18.0 is already installed.
2023-06-03T00:39:38.883783Z	Now using node v12.18.0 (npm v6.14.4)
2023-06-03T00:39:39.058405Z	Started restoring cached build plugins
2023-06-03T00:39:39.070452Z	Finished restoring cached build plugins
2023-06-03T00:39:39.465852Z	Attempting ruby version 2.7.1, read from environment
2023-06-03T00:39:40.876693Z	Using /opt/buildhome/.rvm/gems/ruby-2.7.1
2023-06-03T00:39:41.817819Z	Using PHP version 5.6
2023-06-03T00:39:41.909048Z	5.2.5 is already installed.
2023-06-03T00:39:41.925806Z	Using Swift version 5.2.5
2023-06-03T00:39:41.926266Z	Started restoring cached node modules
2023-06-03T00:39:41.937328Z	Finished restoring cached node modules
2023-06-03T00:39:42.260116Z	Installing NPM modules using NPM version 6.14.4
2023-06-03T00:39:44.005582Z	npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
2023-06-03T00:39:55.621633Z	
2023-06-03T00:39:55.622513Z	> akash-network-website@1.1.0 postinstall /opt/buildhome/repo
2023-06-03T00:39:55.622701Z	> hugo-installer --version otherDependencies.hugo --extended --destination node_modules/.bin/hugo
2023-06-03T00:39:55.622842Z	
2023-06-03T00:39:55.711382Z	(node:1184) ExperimentalWarning: The ESM module loader is experimental.
2023-06-03T00:39:55.72907Z	internal/modules/run_main.js:54
2023-06-03T00:39:55.729358Z	    internalBinding('errors').triggerUncaughtException(
2023-06-03T00:39:55.729524Z	                              ^
2023-06-03T00:39:55.729648Z	
2023-06-03T00:39:55.729771Z	Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
2023-06-03T00:39:55.729895Z	    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:720:11)
2023-06-03T00:39:55.730017Z	    at Loader.resolve (internal/modules/esm/loader.js:97:40)
2023-06-03T00:39:55.730133Z	    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
2023-06-03T00:39:55.730252Z	    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
2023-06-03T00:39:55.730381Z	    at link (internal/modules/esm/module_job.js:41:36) {
2023-06-03T00:39:55.73049Z	  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
2023-06-03T00:39:55.730597Z	}
2023-06-03T00:39:55.747667Z	npm ERR! code ELIFECYCLE
2023-06-03T00:39:55.74791Z	npm ERR! errno 1
2023-06-03T00:39:55.748886Z	npm ERR! akash-network-website@1.1.0 postinstall: `hugo-installer --version otherDependencies.hugo --extended --destination node_modules/.bin/hugo`
2023-06-03T00:39:55.749189Z	npm ERR! Exit status 1
2023-06-03T00:39:55.749399Z	npm ERR! 
2023-06-03T00:39:55.749555Z	npm ERR! Failed at the akash-network-website@1.1.0 postinstall script.
2023-06-03T00:39:55.749729Z	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2023-06-03T00:39:55.794768Z	
2023-06-03T00:39:55.795059Z	npm ERR! A complete log of this run can be found in:
2023-06-03T00:39:55.795247Z	npm ERR!     /opt/buildhome/.npm/_logs/2023-06-03T00_39_55_783Z-debug.log
2023-06-03T00:39:55.810412Z	Error during NPM install
2023-06-03T00:39:55.814596Z	Failed: build command exited with code: 1
2023-06-03T00:39:56.578554Z	Failed: error occurred while running build command
````

6. I clicked the `Re-run` button there
![image](https://github.com/akash-network/website/assets/107317698/fda01b10-f069-4436-9e34-20c5f63bea01)

Doesn't seem to be doing anything :man_shrugging: 

7. Could also click `Retry deployment` in Cloudflare for [that](https://dash.cloudflare.com/fa0186293ce6df59a669b879db591361/pages/view/website/182ec858-7388-4bdf-a5d5-78373794c408) job

![image](https://github.com/akash-network/website/assets/107317698/d7d50e07-c557-434c-8064-2e83ad757264)

But thought that it was an old one, which might have been even failing for a reason.

## Next steps

Checking whether the automation is generally working by merging couple of fixes in this PR https://github.com/akash-network/website/pull/235

**Comment by ghost** [comment]
## Observations so far

1. Merged the PRs (#235, #236 and the final one - #237)
2. It triggered the build job automatically (e.g. for the PR #237 ) https://github.com/akash-network/website/actions/runs/6002416404/ )
3. The build job takes less than `5 minutes`
4. Only the [first](https://github.com/akash-network/website/pull/235/files#diff-07867a16a16f0d26e01253a231f68c09ec6efa39f4b5ebc5191dc2cfe0208a97R57) fix **was** reflected at the Akash Website => the link to `sig-economics` page:

![image](https://github.com/akash-network/website/assets/107317698/37de1cf3-1179-43fd-996c-b11ae56ecf7c)

- `Page not found :(` - `The page you are looking for doesn't exist or has been moved.`

![image](https://github.com/akash-network/website/assets/107317698/2006e9d9-6c91-4fd3-95ca-62dd071f9e85)


The other two attempts #236 #237 to fix the link to `Stable payments & Settlement` - failed.

5. Purging Cloudflare cache doesn't help


## Thoughts

Maybe the page is too nested?

**Comment by ghost** [comment]
Tested the nesting issue theory:
https://github.com/akash-network/website/pull/238

And it **confirms**!

https://akash.network/community/core-groups/stable-payments-and-take-rate/ - **Works**! :partying_face: 

![image](https://github.com/akash-network/website/assets/107317698/e5336690-d4f2-4aae-b1d1-b6d8a5b2af17)


https://akash.network/community/core-groups/sig-economics/stable-payments-and-take-rate/ - Does not - `Page not found :(`

![image](https://github.com/akash-network/website/assets/107317698/ab5b9522-b923-46ba-8081-1bcbb073022e)


Looks like we can't nest the pages too much, max depth is 3 levels as it seems.

```
website/
content/
en/
community/core-groups/sig-economics
```

Anything that goes deeper than that, e.g. `<1>/<2>/<3>/<4>`  - `<4>` will return 404 Page not found

There might be some particular setting for that in Hugo, but I have not seen them to be showing deeper than 3 levels in their docs https://gohugo.io/content-management/sections/?search-input=levels

**Comment by ghost** [comment]
Ok that was not the nesting limit, but the way how Hugo works :rofl: 

> You need to rename the `index.md` pages to `_index.md` if you want it to have child pages. This tells Hugo that it is a section / list page.
> 
> Source: https://discourse.gohugo.io/t/pages-in-nested-content-directory-vanish-completely/24915


PR https://github.com/akash-network/website/pull/239

Et voilà!

![image](https://github.com/akash-network/website/assets/107317698/c9dcb93a-9863-47e9-b4cf-f63006f16be9)

**Comment by ghost** [comment]
The fix is to just rename all `index.md` to `_index.md`  under the `website/content/en/community/core-groups/*/` (and wherever applicable) for them to have an access to the child pages.

Automation is working.

Closing.
